name: Automated Release

on:
  workflow_dispatch: {}
  push:
    branches: [ main ]

jobs:
  build:
    uses: ./.github/workflows/build.yml
  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/download-artifact@v3
      with:
        name: Mod
    - name: Set Environment Variables
      run: |
        echo "workshop_id=$(cat About/PublishedFileId.txt)" >> $GITHUB_ENV
        cd ..
        echo "repo_folder=$(ls)" >> $GITHUB_ENV
    - name: steam-workshop-upload
      if: env.workshop_id
      uses: weilbyte/steam-workshop-upload@v1
      with: 
        appid: 294100 # Rimworld's Steam App ID
        itemid: ${{env.workshop_id}} # Your mod's Steam Workshop ID
        path: ../${{env.repo_folder}} # Path to your mod's folder from repository root
      env:
        STEAM_USERNAME: ${{ secrets.STEAM_USERNAME }} # Your Steam username
        STEAM_PASSWORD: ${{ secrets.STEAM_PASSWORD }} # Your Steam password
        STEAM_TFASEED: ${{ secrets.STEAM_TFASEED }} # Your Steam Guard 2FA shared secret (Optional)
    - run: |
        cd ..
        7z a ${{env.repo_folder}}.zip ${{env.repo_folder}}
    - name: Create Github Release
      uses: Hs1r1us/Release-AIO@v1.0
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref }}
        asset_files: ../${{env.repo_folder}}.zip