name: Upload

on:
  workflow_dispatch: {}
  release:
    types: [published, prereleased]
  pull_request:
    branches: [ main ]


jobs:
  build:
    uses: ./.github/workflows/build.yml
  upload:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/download-artifact@v3
      with:
        name: Mod
    - name: Release
      uses: softprops/action-gh-release@v1
      with:
        files: "**"
        prerelease: true
    - name: Set Environment Variables
      run: |
        echo "workshop_id=$(cat About/PublishedFileId.txt)" >> $GITHUB_ENV
        cd ..
        echo "repo_folder=$(ls)" >> $GITHUB_ENV
    - name: steam-workshop-upload
      if: env.workshop_id
      uses: weilbyte/steam-workshop-upload@v1
      with: 
        appid: 294100 # Rimworld's Steam App ID
        itemid: ${{env.workshop_id}} # Your mod's Steam Workshop ID
        path: ${{env.repo_folder}} # Path to your mod's folder from repository root
      env:
        STEAM_USERNAME: ${{ secrets.STEAM_USERNAME }} # Your Steam username
        STEAM_PASSWORD: ${{ secrets.STEAM_PASSWORD }} # Your Steam password
        STEAM_TFASEED: ${{ secrets.STEAM_TFASEED }} # Your Steam Guard 2FA shared secret (Optional)