name: Upload

on:
  workflow_dispatch: {}
  release:
    types: [published, prereleased]
  pull_request:
    branches: [ main ]


jobs:
  build:
    uses: ./.github/workflows/build.yml
  upload:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - run: cd ..
    - run: echo $(ls)